# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Data Science with R
tagline:          'by Garrett Grolemund'
description:      "Data Science with R is a new book by O'Reilly Media. Pre-order your copy at <a href='http://shop.oreilly.com/product/0636920028574.do#'>shop.oreilly.com</a>."
url:              http://garrettgman.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Garrett Grolemund'
  url:            https://twitter.com/StatGarrett

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/garrettgman/garrettgman.github.io
